export interface ClienteInterface{
accion?: string;
administrador?: string;
aniosexp?: string;
apoderada?: string;
cantidadtb?: string;
competenciabpa?: string;
competenciabpm?: string;
correo?: string;
correoad?: string;
correoap?: string;
correodt?: string;
correogc?: string;
correogg?: string;
correogp?: string;
correojl?: string;
direccion?: string;
directort?: string;
distrito?: string;
dpto?: string;
emailcor?: string;
eqpmed2017?: string;
eqpmed2018?: string;
eqpmed2019?: string;
eqpmed2020?: string;
estadocon?: string;
facebook ?: string;
facturacion2017?: string;
facturacion2018?: string;
facturacion2019?: string;
facturacion2020?: string;
fechafinbpa?: string;
fechafinbpm?: string;
fechaini?: string;
fechainibpa?: string;
fechainibpm?: string;
fonofijo1?: string;
gcomercial?: string;
ggeneral?: string;
gproduccion?: string;
jlogistica?: string;
linkedin?: string;
ncomercial?: string;
nombre?: string;
numcoti?: string;
otcargo?: string;
plazoclie?: string;
productosco2017?:string;
productosco2018?:string;
productosco2019?: string;
productosco2020?: string;
productosfa2017?: string;
productosfa2018?: string;
productosfa2019?: string;
productosfa2020?: string;
productosor2017?: string;
productosor2018?: string;
productosor2019?: string;
productosor2020?: string;
provincia?: string;
reactivos2017?: string;
reactivos2018?: string;
reactivos2019?: string;
reactivos2020?: string;
responsable?: string;
rsocial?: string;
ruc?: string;
servicio?: string;
status?: string;
telefono?: string;
telefonoad?: string;
telefonoapo?: string;
telefonodt?: string;
telefonogc?: string;
telefonogg?: string;
telefonogp?: string;
telefonojl?: string;
tipocon?: string;
web?: string;
uid?:string;
}

 